const data = {
    products: [
        {
          name: 'Burger',
          slug: 'burger',
          category: 'Fast food',
          image: '/images/p1.jpg', // 679px × 829px
          price: 120,
          countInStock: 10,
          brand: 'Nestle',
          rating: 4.5,
          numReviews: 10,
          description: 'Delicious burger',
        },
        {
          name: 'Cake',
          slug: 'delicious-cake',
          category: 'Snacks',
          image: '/images/p2.jpg',
          price: 250,
          countInStock: 20,
          brand: 'Britannia',
          rating: 4.0,
          numReviews: 10,
          description: 'delicious cake',
        },
        {
          name: 'dosa',
          slug: 'pain-dosa',
          category: 'fast food',
          image: '/images/p3.jpg',
          price: 25,
          countInStock: 15,
          brand: '',
          rating: 4.5,
          numReviews: 14,
          description: 'high quality product',
        },
        {
          name: 'pizza',
          slug: 'dominno\'s pizza',
          category: 'fast food',
          image: '/images/p4.jpg',
          price: 65,
          countInStock: 5,
          brand: 'Domino\'s',
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
        {
            name: 'pizza2',
            slug: 'dominno\'s pizza',
            category: 'fast food',
            image: '/images/p4.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Domino\'s',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            name: 'Burger2',
            slug: 'burger',
            category: 'Fast food',
            image: '/images/p1.jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'Nestle',
            rating: 4.5,
            numReviews: 10,
            description: 'Delicious burger',
          },
      ], 
};
export default data;